services:
  web:
    build:
      context: ./stockai-web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    environment:
      - DB_PATH=/data/stocks.db
    volumes:
      - ./data:/data
