services:
  web:
    build:
      context: ./stockai-web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    environment:
      - DB_PATH=/data/stocks.db
      - SCHEDULED_UPDATE_ENABLED=true
      - SCHEDULED_UPDATE_TIMEZONE=America/Chicago
    volumes:
      - ${DB_DIR:-./data}:/data # fall back to ./data path locally
